version: '3'
services:
  dii-master:
    image: dii
    container_name: dii-master
    command: ["./dii", "-type", "master", "-addr", "dii-master"]
    tty: true
    stdin_open: true
    ports:
      - "5000:5000"

  worker-1:
    image: dii
    container_name: worker-1
    command: ["./dii", "-type", "worker", "-addr", "worker-1", "-port", "50001", "-master", "dii-master:5000"]
    ports:
      - "50001:50001"

